[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "8b74a874fd0d6181350d76ee62210adf5722f595"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "22eed5384462a32066f77bb02c0fa504a510ff213bb893d6e80f4ae4dd3b5d77"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "03afe80a3fb218830c4d3fd7d7d894ad35a9e45f"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "fa07c845cd6ce378a5c17eb2a60763ea245c10f1c1d8c7bb88f7e5259beaf7be"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "6275acddf5e4f989df510b5656b83c63c4c8a149"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "8ae9eb7100d3d0a6b527b178dd86b1d1f5758381f727ff4c57733e9419e73b5c"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.armv7l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "efcc5243aefbf3284328dd62bca15037ae456734"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "d38d8070ff68b977c82bd3360c2c9db6320e36f7c366d35fa29fb6089657706e"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.armv7l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "b4a3a93efe399536b9df038ab3ebdb7cd0365c33"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "ecf61c41a8af6c04fd5a5b8b4932bf888c8f6bb5c2f17b6955fb9a70887b52ca"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "a257890f5b0669ec6f27a2ee963db999f1937340"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "ddc6fc8bc131fc43b0ba8d405456c5bf8f320b622d462d0921931439f092ba75"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "1d9c6aebbdee3f318e9645c1bd87828c6ae668b5"
os = "windows"

    [[Pixman.download]]
    sha256 = "cc845f51b364c7eda3c0187e8732c88a3d622a1bb9f173155af6da797ef75364"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "9ea7d9a54d0770310bdc975d608ff12fb8fab0d6"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "56f1cfc4af61d43c554ea43aa7540c9a2f8d995030e04d59e3576bb6be569d1d"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "e6329a21a26d2fb8e8ab47aae9df740362edea97"
os = "macos"

    [[Pixman.download]]
    sha256 = "67fcfb8ef166ea46c35e618ded5d270926c00ba07fe9de058716ec8fd4d93329"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.x86_64-apple-darwin14.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "36977a6921a38080ab1d9aafd62063345bd314cd"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "edbe58cc7ff1f442a9d6bd65d6aa93c7637cef12acac3076cd00ab4eb3a75477"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "e7a5f16341b691313ff13eae74831fb5eda39857"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "10c573662dd1a66c762e1c687a68a126678a792cd3868e1dfba492e67767ec42"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "b2b5d1db823610f8c5b23b25fce5e1584b87da48"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "0579a485d5bbc59f378434b71a4288d9761d89dbbc70c34b07562ac5d1c25822"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "829138e071c8afacb2c6d6134e74465203821087"
os = "windows"

    [[Pixman.download]]
    sha256 = "c4aa5300434c228064b976cec60aa28595c05698abcce370fba194e9ab3d9dd7"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+4/Pixman.v0.38.4.x86_64-w64-mingw32.tar.gz"
