[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "045489ac58bb0baeedf9a4af5b194c5345867a79"
os = "macos"

    [[Pixman.download]]
    sha256 = "fb3d8445d5c8dee76e84db0c2306a188fced61a041ff35ea4d30568e2e206b74"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.aarch64-apple-darwin.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "2356d617a91dfbd579091036514e3831242f29e5"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "e2858b40008367f24443d62ffe3fd366f02cdffbc21a6240b577ce8b5c96c5ff"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "fdf0cf51d92ec9801bded5370bf71b00097934d6"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "cc3abd83bcaf68117e3934e596366ae6e825cd3a42edcfea0417981bea713bc8"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "bd738ab127c2fc84c66898c7a07517cf35ad7c1f"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "cf0baeb12fe4bfd19e0e60945378d24050774a172f73610aa4caa1c8750bf9c2"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.aarch64-unknown-freebsd.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6bb8c7238399e5d3c3f34918d07a451cb4f2c5e4"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "c09ebf0eaa361e3d957b87f67dda8825c13f294d156d1f81e0cf65f9e97be707"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.armv6l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e1e6e546ca3715cb51cdb07313ee0156793a8a34"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "87eeb2ece7a07bbcf9b428c9d8d3d53b6968d548dc854f7226efcd72a46ed697"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.armv6l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b65208e6a803e9d23d727f093b11eca254190024"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "3d41cb8bb65748d29d1fb51dc425689f7a9fdddfda53961f6c6bd485e55fbbec"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.armv7l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df93cf72b9be634d1ed45fe66449fa4c5ca0e120"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "40a9059105465a3b50899b1c66919a7d45f0e20db1fc97c3efc073814790a891"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.armv7l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "fa89909e640f8a617970b8f9345991d442733532"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "4d7a542b4784097d9d4d5ce88c17a2248a8333b39ea7201ac2851db2278da624"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "7030e9d418d0aab1e225ac6ed91706881512d2ab"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "c9712074c7043a89770e0f79f5e9692fc7869ed416150967af73477f5a980ecf"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "4e4cb0922ef0f73bfb9c68487d65f9fbea5d5346"
os = "windows"

    [[Pixman.download]]
    sha256 = "eb4886bfdea584fbd584c1223b74a7d08c3c9ebe95956df1c3c809f58ca97e70"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "6d97ed1dd30139bddfbc7f9ac977cc753715fef5"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "686110ce052b54e8681025ab12d3bae1c6ab05dc9ab1050bfdfc1868ab382c73"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "riscv64"
git-tree-sha1 = "510bb7c46497730b1d4a1d3a21eb4d97eeb94369"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "ca1be780fc88b91873d59a2ce6281a59f0a5790313c96202ad051b5e923d59e3"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.riscv64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "c0b21804ebd104328b39c8e118c6f9494513a109"
os = "macos"

    [[Pixman.download]]
    sha256 = "6a4a71a3944b020c37eea2546e64c1cf03b7c4514379c65f4f8a659bee99e984"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.x86_64-apple-darwin.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "60474b674d6d76e79c1fda291db399771c910e0d"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "72fda8a911b317751857427bb17d76335ef6f9cd4068427ce253bb2ee187fefe"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "777a4e42bd4eb0caa24716ff3a372dbf13aeba94"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "f868abafb9c74473cbc5aa19e1ac8612db81c2eb49d3b0be78e8d98e9831b621"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "7a1fb56d3556e003d60099ac43e11318e31f0395"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "e946d84b7b9668fba1a75ec0c4e4ad72177106efe7ac76021d60c32573170dc7"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.x86_64-unknown-freebsd.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "dcb262d19d1c1436bada5c00c36f1c49cd23ea2e"
os = "windows"

    [[Pixman.download]]
    sha256 = "779d7ec320a8a1c23ab6308bd2b3cccb02f8e82cc37ccf2cb6226add399b6097"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.0+0/Pixman.v0.46.0.x86_64-w64-mingw32.tar.gz"
