[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "e9b0851a146c20a7f62a143787b3c15b54771d22"
os = "macos"

    [[Pixman.download]]
    sha256 = "c5a28f2ca8da4ef81505758b8f13ee891c557b5a708a5a4c9d4f1b838d8ee250"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.aarch64-apple-darwin.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "dcc6cc9cd217219330d8184ce3b38f2bfbc12a12"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "169420acad17eb30ae555162ad8c3a0a5a790d033aa6bc0413709299103261a5"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "4de9240dd14751ab100b57d117ee3fc35b463f3a"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "4959c40236ea45f588f69c94afb69fe0edca9de5d28d5eb31c0d9dd773ba94f5"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "1f1af68438d6d5803ab358b72e03d0e39b8c57dd"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "210cbd6acfe92a4f14f8170c448bdb3f7e8217d1e3b6eb318c315bdbc29b670b"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.aarch64-unknown-freebsd.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b325772daafe4d12da7ac58df78f6028aaa74aef"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "dc84fa7a412d590a720c23e7a038b88e564232249492da32d65c5d67244aab2c"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.armv6l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "daf71e35e050e2d5852de312c60764238db8eb8f"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "9cdc8f80ab5afcd53f9123a2f2f990f479b393a84c53a3c2e1471dcb348e8e72"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.armv6l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2fc92fd881864f7422b55a7793148790fd3f95aa"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "e63d63603366ad4b1713940419ad0182931e61272213086a454c3e7753ce67f4"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.armv7l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "badffc22201d20e29ea6e66ba29dcd7b486d22a0"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "9b358837055fe6c306e4f0c4fb31dfe6daaf43b75143b2119440df1822c852ec"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.armv7l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "5f977e83820d8cd65c05e1323acbf11cf570289c"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "d681df21e3958795a9c9bfa4626eb10f6f5a9ee460a161d8df77ffeaaca64366"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "e5c87e042fd0639b69fc6d799bc9066b075002fd"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "4a39df6335792a2a406ecd9ea4031d9307b08c19fd1b1fc827a9f61f86cacb40"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "80dd8efd50dc43437104180c4a282c1aedd0abed"
os = "windows"

    [[Pixman.download]]
    sha256 = "868bfb7329393573fdca1ec878d1e5921c45a5d71929a59f6d81c86412739195"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "d53357b59235e26a69312b0c0c9befe37f600a89"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "a9f3c919371fc5972bcf4e780c3742d170fea2b23be1e81eb7be75bb969112a6"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "riscv64"
git-tree-sha1 = "f383d3945543979cb2a501f978160c722749fad4"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "a8e40ab78256ed9c08ea79f6ef3769319d719b21dd3a810c9b90d2003bcd1174"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.riscv64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "b9c72917c9dcf87b370369316f050192988d7a42"
os = "macos"

    [[Pixman.download]]
    sha256 = "b6c8600e050ba0cf16a54cad9bb564ad2372d42d1a4c5dcf7e127e36a7a0d270"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.x86_64-apple-darwin.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "57aad714583e6859885b67e58ce5626117a1703f"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "ac2e155bc21fb157ffcb9be31e918d3ce53ab89c3bfa7022e39e714840241d04"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "b80d7f538b7d29cf0cf49c0a2fe0e9e4a81e14c2"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "eb974caab47d603030f503ef6245956a958254935b9bd08df27f65cd22124ffd"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "f5e5af08eb2800e9660f2ecbb9b69e005a7d9db8"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "98f410acc8fe11e258d89a3fce0067d364abfcc083527cddabd3df2800e6e1c9"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.x86_64-unknown-freebsd.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "21e2bd3c5c2197c83a5a9bab8b2339512abc57de"
os = "windows"

    [[Pixman.download]]
    sha256 = "f7ff9d9fa6e016f94ef6bdc6a58e2dc48082c4ab2c4e183ed74dc0207b6decdf"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.46.2+0/Pixman.v0.46.2.x86_64-w64-mingw32.tar.gz"
