[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "07e6bd5ae846b525d0c43be96788967cfccb923b"
os = "macos"

    [[Pixman.download]]
    sha256 = "347fd6771a69115f1ce82bf4848cd505d3f12d15478301702b4f90b2f72992bd"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.aarch64-apple-darwin.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "ff0251871a1c66f0ac44feab4821b12f0825f3af"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "caa79efa919c096e5feda0d53e541ae3cee8a9b408e3aa6305f89ff1e80571b7"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "985286c4e19fa4a0fc4382a4417b90b5bd1ecb0a"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "561ddaf9b2bbb68c3be95cb22cd231d6f392632c6a8aaa71f215f8f1f0426880"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0765a60c29935262564567fabe72681e3e0b6b92"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "bb56bba0bcdad5c2bfb9e917e00d75e06a38e69e8c3742ce9433f88265b1a1aa"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.armv6l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "076b8e338a115936de61c2603a9b069c851af627"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "2b7a96a6b6ada14e3095e364e0fe51e99593a815e0797ecdacb3720a4e5f4715"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.armv6l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04e5df6e908df26e6f574df785b23fdc275b5677"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "0739d818b4ffeefc31a60c863c442cb2415519cf45c92c4cb6eeea10707df2e6"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.armv7l-linux-gnueabihf.tar.gz"
[[Pixman]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fbaab9ac758a26570103be303e4e85a3499d7307"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "f3449470362aeb953d69cfe907fecc812991f6ed19a20ad52e50075ba1a2eb01"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.armv7l-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "c9a52db1952ed5791f054ee52372ebb25eec8ea6"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "7a07c2e29d63f46f71b5a7e79337b6959a6713a9e24b6d29b6ebe72ed0b26eb8"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "7a25c28b607d9ff5a615e23ce3e7e014c0b6af16"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "fa942f6660c7b75fc1c146f9754bc49ccbad67013b4edcda7f401c7d97a5ea23"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "56029da186fcde86b731aff554b75d796f950fec"
os = "windows"

    [[Pixman.download]]
    sha256 = "e69cc618efffab556bc41b7d68443568a075ef69ed35b966229882fdda90e9a9"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "701454b5b0b2a21744eebc3bd0666b5b9ea9f975"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "f22c0b360f1a83a1a369c8bdfc570627d4771c394185abf63c30fdec28496373"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "01634e770ae64009bdfef5564794522bc669be47"
os = "macos"

    [[Pixman.download]]
    sha256 = "4bfff060b830844c75e0da89fb25e2c6ad21215ccd1048572d2e0f6bc9324727"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.x86_64-apple-darwin.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "b3ddd583e7aec92a77cf5961fad01fd7063c1d40"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "64e2799eb818262710115e76ae891b8a4572bd8e7cb3a6d9cd886cc1d393cc7e"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "ba075e723446a08bffea7461f85f5cd15d06dda7"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "9eb8948f7eb6c4189fa179e6c962f68b455d31312aca023ea60502f004a4b0ed"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "7940191749db99cdc87a9a48f3b410b13a877341"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "935aa0026aeda8430aed7e43127732883aa245cf737d7e8d653a8fae42f44e79"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.x86_64-unknown-freebsd.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "65344baf0f37436ecadc11a95f5470ed45b7817b"
os = "windows"

    [[Pixman.download]]
    sha256 = "2f624a5e01ac6531b9e59c58cf26a7d223522f7cf74937ec8785d6564af6e107"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.43.4+0/Pixman.v0.43.4.x86_64-w64-mingw32.tar.gz"
