[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "ac5a55a36a7c299cee39445a152efd8fa620d98b"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "d01db68d130fd50fd91d5aef3145da16544b816f8d41f50bc4132750f9da5465"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.x86_64-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "fa6038b46e09fe0d11d61c311893ec42f0822315"
os = "macos"

    [[Pixman.download]]
    sha256 = "997ad4ff05ade60244c4d4d899c3e345149ef3f162676743686b4edc33cbc22c"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.x86_64-apple-darwin14.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "34927ae3ad0b770cef40b9c98a7ce9a4437cd090"
os = "windows"

    [[Pixman.download]]
    sha256 = "255f62ca7ad19db87529372500c65b74b05319672d8c106723eaa663598963de"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.i686-w64-mingw32.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "7d2e2a00b9b5607e4059889e30ea9486a76e174e"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "b10978d54265b3e2404847ac254c8503d15312bd10dfa38e1df004e0e98e6341"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.aarch64-linux-gnu.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "b9573c81626c4f845e0b2522cf2a1de6adeec34d"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "25ad0393f3322cefd6214b4696844f34642716bcad8b8bca40dd6c03149ba029"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.i686-linux-musl.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "fa8b636d4bddee992a85fea4e310fc767f55db5e"
os = "windows"

    [[Pixman.download]]
    sha256 = "476ce3140c5996060224ed72790435f71ec13f2b3245e51a7810ed67f4cb3ebe"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.x86_64-w64-mingw32.tar.gz"
[[Pixman]]
arch = "powerpc64le"
git-tree-sha1 = "4002367565a9f18431e02bc0d11646966465087b"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "a8252305e85a916bf2f9aeb0bba78420fd43b0c8841ab5e19d9fba5ae0f966cf"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.powerpc64le-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "790e21504c2cdfaf89e4073bda93267ef10ec1a7"
os = "freebsd"

    [[Pixman.download]]
    sha256 = "8e82a24b94433b557601e5801dcf75e72c8bdd943a49b2d2c36fe124fc996d92"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "6ae8cd45c456e1dca61b82a942149b44e541cf98"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "59cbd1ec02ec04e95417350ea405b6599cd41fa489e1f753554c034696ef5741"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.arm-linux-musleabihf.tar.gz"
[[Pixman]]
arch = "aarch64"
git-tree-sha1 = "ffc0db63950611426a980640977503c41918863b"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "8ad39c3b077f98d7a8325e91a9983c53f2fb4691e8248fe5b381f631058d0d80"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.aarch64-linux-musl.tar.gz"
[[Pixman]]
arch = "i686"
git-tree-sha1 = "7c234db8b8f67bfc4f3339431732d2c95b3750bf"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "a3a97572cf7686d7469cb4753f77b287dab5e1215b24d3d1a3d826b523e2545d"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.i686-linux-gnu.tar.gz"
[[Pixman]]
arch = "x86_64"
git-tree-sha1 = "3dd4418166f399966fad14fc54d2587db3867827"
libc = "musl"
os = "linux"

    [[Pixman.download]]
    sha256 = "f6fd9c5892e2aba8e9109c46d6a8e73b525d832b2cf9d637fa4ae79b8d871221"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.x86_64-linux-musl.tar.gz"
[[Pixman]]
arch = "armv7l"
git-tree-sha1 = "72fb40cbe81f8394f72e5b5774984a52eef770ce"
libc = "glibc"
os = "linux"

    [[Pixman.download]]
    sha256 = "725747db5fb6707448eaac52ec53d8c65756688604fec489ab7b9040fe835b68"
    url = "https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/releases/download/Pixman-v0.38.4+0/Pixman.v0.38.4.arm-linux-gnueabihf.tar.gz"
